#!/usr/bin/env node
/**
 * Fix _routes.json generated by Astro Cloudflare adapter
 * Removes incorrect exclusions for server-rendered pages
 */

const fs = require('fs');
const path = require('path');

const routesPath = path.join(__dirname, '../dist/_routes.json');

try {
  const routes = JSON.parse(fs.readFileSync(routesPath, 'utf8'));
  
  // Remove server-rendered pages from exclude list
  const pagesToServe = ['/about', '/partnerships', '/chamber-partnerships', '/business-partnerships'];
  routes.exclude = routes.exclude.filter(route => !pagesToServe.includes(route));
  
  fs.writeFileSync(routesPath, JSON.stringify(routes, null, 2));
  console.log('✅ Fixed _routes.json - removed incorrect exclusions');
} catch (error) {
  console.error('❌ Error fixing routes:', error.message);
  process.exit(1);
}
